In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TravelInsurancePrediction.csv')
df.head()

Age               Employment Type  ... EverTravelledAbroad  TravelInsurance
0   31             Government Sector  ...                  No                0
1   31  Private Sector/Self Employed  ...                  No                0
2   34  Private Sector/Self Employed  ...                  No                1
3   28  Private Sector/Self Employed  ...                  No                0
4   28  Private Sector/Self Employed  ...                  No                0

[5 rows x 9 columns]

In [34]:
df['FrequentFlyer'] = df['FrequentFlyer'].map({'Yes': 1, 'No': 0})
df['EverTravelledAbroad'] = df['EverTravelledAbroad'].map({'Yes': 1, 'No': 0})
df['GraduateOrNot'] =  df['GraduateOrNot'].map({'Yes': 1, 'No': 0})
df["Employment Type"] = df["Employment Type"].map({"Government Sector" : 1, "Private Sector/Self Employed" : 0})

df.head()

Age  Employment Type  ...  EverTravelledAbroad  TravelInsurance
0   31                1  ...                    0                0
1   31                0  ...                    0                0
2   34                0  ...                    0                1
3   28                0  ...                    0                0
4   28                0  ...                    0                0

[5 rows x 9 columns]

In [35]:
df = df[['Age','GraduateOrNot','AnnualIncome','FamilyMembers','TravelInsurance']]

In [36]:
from sklearn.model_selection import train_test_split

# 인자로 입력받은 DataFrame을 복사 한 뒤 Time 컬럼만 삭제하고 복사된 DataFrame 반환
def get_preprocessed_df(df=None):
    df_copy = df.copy()
    return df_copy

In [54]:
# 사전 데이터 가공 후 학습과 테스트 데이터 세트를 반환하는 함수.
def get_train_test_dataset(df=None):
    # 인자로 입력된 DataFrame의 사전 데이터 가공이 완료된 복사 DataFrame 반환
    df_copy = get_preprocessed_df(df)
    # DataFrame의 맨 마지막 컬럼이 레이블, 나머지는 피처들
    X_features = df_copy.iloc[:, :-1]
    y_target = df_copy.iloc[:, -1]
    # train_test_split( )으로 학습과 테스트 데이터 분할. stratify=y_target으로 층화추출 기반 균등분할
    X_train, X_test, y_train, y_test = \
    train_test_split(X_features, y_target, test_size=0.2, random_state=0, stratify=y_target)
    # 학습과 테스트 데이터 세트 반환
    return X_train, X_test, y_train, y_test

In [55]:
X_train, X_test, y_train, y_test = get_train_test_dataset(df)

In [56]:
print('학습 데이터 레이블 값 비율')
print(y_train.value_counts()/y_train.shape[0] * 100)
print('테스트 데이터 레이블 값 비율')
print(y_test.value_counts()/y_test.shape[0] * 100)

학습 데이터 레이블 값 비율
0    64.254248
1    35.745752
Name: TravelInsurance, dtype: float64
테스트 데이터 레이블 값 비율
0    64.321608
1    35.678392
Name: TravelInsurance, dtype: float64


In [57]:
# 평가 함수
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def get_clf_eval(y_test, pred):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    print('오차 행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}, F1: {3:.4f}'.format(accuracy, precision, recall, f1))

In [58]:
import time
def get_model_train_eval(model, ftr_train=None, ftr_test=None, tgt_train=None, tgt_test=None):
    start_time = time.time()
    model.fit(ftr_train, tgt_train)
    pred = model.predict(ftr_test)
    get_clf_eval(tgt_test, pred)
    print("수행 시간: {0:.1f} 초 ".format(time.time() - start_time))

In [59]:
from lightgbm import LGBMClassifier

lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
get_model_train_eval(lgbm_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

오차 행렬
[[233  23]
 [ 54  88]]
정확도: 0.8065, 정밀도: 0.7928, 재현율: 0.6197, F1: 0.6957
수행 시간: 0.9 초 


In [60]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=1000,n_jobs=-1)
get_model_train_eval(rf_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

오차 행렬
[[234  22]
 [ 54  88]]
정확도: 0.8090, 정밀도: 0.8000, 재현율: 0.6197, F1: 0.6984
수행 시간: 3.0 초 


In [61]:
from sklearn.preprocessing import StandardScaler

def get_preprocessed_df(df=None):
    df_copy = df.copy()
    scaler = StandardScaler()
    amount_n = scaler.fit_transform(df_copy['AnnualIncome'].values.reshape(-1, 1))
    # 변환된 Amount를 Amount_Scaled로 피처명 변경후 DataFrame맨 앞 컬럼으로 입력
    df_copy.insert(0, 'AnnualIncome_Scaled', amount_n)
    # 기존 Time, Amount 피처 삭제
    df_copy.drop(['AnnualIncome'], axis=1, inplace=True)
    return df_copy

In [62]:
X_train, X_test, y_train, y_test = get_train_test_dataset(df)

In [63]:
rf_clf = RandomForestClassifier(n_estimators=1000,n_jobs=-1)
get_model_train_eval(rf_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

오차 행렬
[[238  18]
 [ 54  88]]
정확도: 0.8191, 정밀도: 0.8302, 재현율: 0.6197, F1: 0.7097
수행 시간: 3.0 초 


In [64]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=0)
X_train_over, y_train_over = smote.fit_sample(X_train, y_train)
print('SMOTE 적용 전 학습용 피처/레이블 데이터 세트: ', X_train.shape, y_train.shape)
print('SMOTE 적용 후 학습용 피처/레이블 데이터 세트: ', X_train_over.shape, y_train_over.shape)
print('SMOTE 적용 후 레이블 값 분포: \n', pd.Series(y_train_over).value_counts())

SMOTE 적용 전 학습용 피처/레이블 데이터 세트:  (1589, 4) (1589,)
SMOTE 적용 후 학습용 피처/레이블 데이터 세트:  (2042, 4) (2042,)
SMOTE 적용 후 레이블 값 분포: 
 1    1021
0    1021
dtype: int64


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [65]:
rf_clf = RandomForestClassifier(n_estimators=1000,n_jobs=-1)
get_model_train_eval(rf_clf, ftr_train=X_train_over, ftr_test=X_test, tgt_train=y_train_over, tgt_test=y_test)

오차 행렬
[[230  26]
 [ 52  90]]
정확도: 0.8040, 정밀도: 0.7759, 재현율: 0.6338, F1: 0.6977
수행 시간: 3.3 초 


In [69]:
from sklearn.ensemble import GradientBoostingClassifier

gb_clf = GradientBoostingClassifier(random_state=0)
gb_clf.fit(X_train , y_train)
gb_pred = gb_clf.predict(X_test)
gb_accuracy = accuracy_score(y_test, gb_pred)

get_model_train_eval(gb_clf, ftr_train=X_train_over, ftr_test=X_test, tgt_train=y_train_over, tgt_test=y_test)

오차 행렬
[[251   5]
 [ 56  86]]
정확도: 0.8467, 정밀도: 0.9451, 재현율: 0.6056, F1: 0.7382
수행 시간: 0.2 초 


In [ ]:
특성: Age, GraduateOrNot, AnnualIncome, FamilyMembers
랜덤 포레스트
정확도: 0.8040, 정밀도: 0.7759, 재현율: 0.6338, F1: 0.6977